name: Planar Rotation Filtered

dataset_path: ${data_path}/rotation/clipped_trajectory

complete_demos:
  - rotation_1
  - rotation_2
  - rotation_3
  - rotation_4
  - rotation_5
  - rotation_6
  - rotation_7
  - rotation_8
  - rotation_9
  - rotation_10
  - rotation_11
  - rotation_12
  - rotation_13
  - rotation_14
  - rotation_15
  - rotation_16
  - rotation_17
  - rotation_18
  - rotation_19
  - rotation_20
  - rotation_21
  - rotation_22
  - rotation_23
  - rotation_24
  - rotation_25
  - rotation_26
  - rotation_27
  - rotation_28
  - rotation_29
  - rotation_30
  - rotation_31
  - rotation_32
  - rotation_33
  - rotation_34
  - rotation_35
  - rotation_36
  - rotation_37
  - rotation_38
  - rotation_39
  - rotation_40
  - rotation_41
  - rotation_42
  - rotation_43
  - rotation_44
  - rotation_45
  - rotation_46
  - rotation_47
  - rotation_48
  - rotation_49
  - rotation_50
  - rotation_51
  - rotation_52
  - rotation_53
  - rotation_54
  - rotation_55
  - rotation_56
  - rotation_57
  - rotation_58
  - rotation_59
  - rotation_60
  - rotation_61
  - rotation_62
  - rotation_63
  - rotation_64
  - rotation_65
  - rotation_66
  - rotation_67
  - rotation_68
  - rotation_69
  - rotation_70
  - rotation_71
  - rotation_72
  - rotation_73
  - rotation_74
  - rotation_75
  - rotation_76
  - rotation_77
  - rotation_78
  - rotation_79
  - rotation_80
  - rotation_81
  - rotation_82
  - rotation_83
  - rotation_84
  - rotation_85
  - rotation_86
  - rotation_87
  - rotation_88
  - rotation_89
  - rotation_90
  - rotation_91
  - rotation_92
  - rotation_93
  - rotation_94
  - rotation_95
  - rotation_96
  - rotation_97
  - rotation_98
  - rotation_99
  - rotation_100
  - rotation_101
  - rotation_102
  - rotation_103
  - rotation_104
  - rotation_105
  - rotation_106
  - rotation_107
  - rotation_108
  - rotation_109
  - rotation_110
  - rotation_111
  - rotation_112
  - rotation_113
  - rotation_114
  - rotation_115
  - rotation_116
  - rotation_117
  - rotation_118
  - rotation_119
  - rotation_120
  - rotation_121
  - rotation_122
  - rotation_123
  - rotation_124
  - rotation_125
  - rotation_126
  - rotation_127
  - rotation_128
  - rotation_129
  - rotation_130
  - rotation_131
  - rotation_132

train_demos:
  - rotation_1
  - rotation_2
  - rotation_3
  - rotation_4
  - rotation_5
  - rotation_6
  - rotation_7
  - rotation_8
  - rotation_9
  - rotation_10
  - rotation_11
  - rotation_12
  - rotation_17
  - rotation_18
  - rotation_19
  - rotation_20
  - rotation_21
  - rotation_22
  - rotation_23
  - rotation_24
  - rotation_25
  - rotation_26
  - rotation_27
  - rotation_28
  - rotation_29
  - rotation_30
  - rotation_31
  - rotation_32
  - rotation_33
  - rotation_34
  - rotation_35
  - rotation_36
  - rotation_37
  - rotation_38
  - rotation_39
  - rotation_40
  - rotation_41
  - rotation_42
  - rotation_43
  - rotation_44
  - rotation_45
  - rotation_46
  - rotation_47
  - rotation_48
  - rotation_49
  - rotation_50
  - rotation_51
  - rotation_52
  - rotation_53
  - rotation_54
  - rotation_55
  - rotation_56
  - rotation_57
  - rotation_58
  - rotation_59
  - rotation_60
  - rotation_61
  - rotation_62
  - rotation_63
  - rotation_64
  - rotation_65
  - rotation_66
  - rotation_67
  - rotation_68
  - rotation_69
  - rotation_70
  - rotation_71
  - rotation_72
  - rotation_73
  - rotation_77
  - rotation_78
  - rotation_79
  - rotation_80
  - rotation_81
  - rotation_82
  - rotation_83
  - rotation_84
  - rotation_85
  - rotation_86
  - rotation_87
  - rotation_88
  - rotation_89
  - rotation_90
  - rotation_95
  - rotation_96
  - rotation_97
  - rotation_98
  - rotation_99
  - rotation_104
  - rotation_105
  - rotation_106
  - rotation_107
  - rotation_108
  - rotation_109
  - rotation_110
  - rotation_111
  - rotation_112
  - rotation_113
  - rotation_114
  - rotation_120
  - rotation_121
  - rotation_122
  - rotation_123
  - rotation_124
  - rotation_125
  - rotation_126
  - rotation_127
  - rotation_128
  - rotation_129
  - rotation_130
  - rotation_131
  - rotation_132

test_demos:
  - rotation_13
  - rotation_14
  - rotation_15
  - rotation_16
  - rotation_74
  - rotation_75
  - rotation_76
  - rotation_91
  - rotation_92
  - rotation_93
  - rotation_94
  - rotation_100
  - rotation_101
  - rotation_102
  - rotation_103
  - rotation_115
  - rotation_116
  - rotation_117
  - rotation_118
  - rotation_119