name: Planar Rotation Filtered

dataset_path: ${data_path}/demonstrations/filtered

complete_demos:
  - demonstration_56
  - demonstration_57
  - demonstration_58
  - demonstration_59
  - demonstration_60
  - demonstration_61
  - demonstration_62
  - demonstration_63
  - demonstration_64
  - demonstration_65
  - demonstration_66
  - demonstration_67
  - demonstration_68
  - demonstration_69
  - demonstration_70
  - demonstration_71
  - demonstration_72
  - demonstration_73
  - demonstration_74
  - demonstration_75
  - demonstration_76

train_demos:
  - demonstration_56
  - demonstration_57
  - demonstration_58
  - demonstration_59
  - demonstration_60
  - demonstration_61
  - demonstration_62
  - demonstration_63
  - demonstration_64
  - demonstration_65
  - demonstration_66
  - demonstration_69
  - demonstration_70
  - demonstration_71
  - demonstration_72
  - demonstration_73
  - demonstration_74
  - demonstration_75
  - demonstration_76

test_demos:
  - demonstration_67
  - demonstration_68