name: Can Spinning SSL

dataset_path: ${data_path}/demonstrations/ssl

complete_demos:
  - demonstration_87
  - demonstration_88
  - demonstration_89
  - demonstration_90
  - demonstration_91 
  - demonstration_92
  - demonstration_93
  - demonstration_94
  - demonstration_95
  - demonstration_96
  - demonstration_97 
  - demonstration_98
  - demonstration_99
  - demonstration_100
  - demonstration_101
  - demonstration_102 
  - demonstration_103
  - demonstration_104 
  - demonstration_105 
  - demonstration_106 
  - demonstration_107
  - demonstration_108 
  - demonstration_109
  - demonstration_110
  - demonstration_111
  - demonstration_112
  - demonstration_113
  - demonstration_114
  - demonstration_115
  - demonstration_116
  - demonstration_117
  - demonstration_118 
  - demonstration_119
  - demonstration_120 
  - demonstration_121
  - demonstration_122
  - demonstration_123
  - demonstration_124
  - demonstration_125
  - demonstration_126
  - demonstration_127 
  - demonstration_128
  - demonstration_129
  - demonstration_130
  - demonstration_131
  - demonstration_132
  - demonstration_133
  - demonstration_134
  - demonstration_135
  - demonstration_136 
  - demonstration_137
  - demonstration_138
  - demonstration_139
  - demonstration_140
  - demonstration_141
  - demonstration_142 
  - demonstration_143
  - demonstration_144 
  - demonstration_145 
  - demonstration_146
  - demonstration_147
  - demonstration_148
  - demonstration_149 
  - demonstration_150
  - demonstration_151

train_demos:
  - demonstration_87
  - demonstration_88
  - demonstration_89
  - demonstration_91
  - demonstration_92
  - demonstration_93
  - demonstration_94
  - demonstration_95
  - demonstration_98
  - demonstration_99
  - demonstration_100
  - demonstration_101
  - demonstration_103
  - demonstration_107
  - demonstration_108 
  - demonstration_109
  - demonstration_110
  - demonstration_111
  - demonstration_112
  - demonstration_113
  - demonstration_114
  - demonstration_115
  - demonstration_116
  - demonstration_117
  - demonstration_118 
  - demonstration_119
  - demonstration_120 
  - demonstration_121
  - demonstration_122
  - demonstration_123
  - demonstration_129
  - demonstration_130
  - demonstration_131
  - demonstration_132
  - demonstration_133
  - demonstration_134
  - demonstration_135
  - demonstration_136 
  - demonstration_137
  - demonstration_138
  - demonstration_139
  - demonstration_140
  - demonstration_141
  - demonstration_142 
  - demonstration_143
  - demonstration_144 
  - demonstration_145 
  - demonstration_146
  - demonstration_147
  - demonstration_148
  - demonstration_149 
  - demonstration_150
  - demonstration_151

test_demos:
  - demonstration_90
  - demonstration_96
  - demonstration_124
  - demonstration_125
  - demonstration_126
  - demonstration_127 
  - demonstration_128