name: Postit Note Sliding SSL

dataset_path: ${data_path}/demonstrations/ssl

complete_demos:
  - demonstration_210
  - demonstration_211
  - demonstration_212
  - demonstration_213
  - demonstration_214
  - demonstration_215
  - demonstration_216
  - demonstration_217
  - demonstration_218
  - demonstration_219
  - demonstration_220
  - demonstration_221
  - demonstration_222
  - demonstration_223
  - demonstration_224
  - demonstration_225
  - demonstration_226
  - demonstration_227
  - demonstration_228
  - demonstration_229
  - demonstration_230
  - demonstration_231
  - demonstration_232
  - demonstration_233
  - demonstration_234
  - demonstration_235
  - demonstration_236
  - demonstration_237
  - demonstration_238
  - demonstration_239
  - demonstration_240
  - demonstration_241
  - demonstration_242
  - demonstration_243
  - demonstration_244
  - demonstration_245
  - demonstration_246
  - demonstration_247
  - demonstration_248
  - demonstration_249
  - demonstration_250
  - demonstration_251
  - demonstration_252
  - demonstration_253
  - demonstration_254
  - demonstration_255
  - demonstration_256
  - demonstration_257
  - demonstration_258
  - demonstration_259
  - demonstration_260
  - demonstration_261
  - demonstration_262
  - demonstration_263
  - demonstration_264
  - demonstration_265
  - demonstration_266
  - demonstration_267
  - demonstration_268
  - demonstration_269
  - demonstration_270
  - demonstration_271
  - demonstration_272
  - demonstration_273

train_demos:
  - demonstration_210
  - demonstration_211
  - demonstration_212
  - demonstration_213
  - demonstration_214
  - demonstration_217
  - demonstration_218
  - demonstration_219
  - demonstration_220
  - demonstration_221
  - demonstration_222
  - demonstration_223
  - demonstration_224
  - demonstration_225
  - demonstration_226
  - demonstration_227
  - demonstration_228
  - demonstration_229
  - demonstration_230
  - demonstration_231
  - demonstration_234
  - demonstration_235
  - demonstration_236
  - demonstration_237
  - demonstration_238
  - demonstration_239
  - demonstration_240
  - demonstration_241
  - demonstration_242
  - demonstration_243
  - demonstration_244
  - demonstration_245
  - demonstration_246
  - demonstration_247
  - demonstration_248
  - demonstration_249
  - demonstration_250
  - demonstration_251
  - demonstration_252
  - demonstration_253
  - demonstration_254
  - demonstration_256
  - demonstration_257
  - demonstration_258
  - demonstration_259
  - demonstration_260
  - demonstration_261
  - demonstration_262
  - demonstration_263
  - demonstration_264
  - demonstration_265
  - demonstration_266
  - demonstration_267
  - demonstration_268
  - demonstration_269
  - demonstration_270
  - demonstration_271
  - demonstration_272
  - demonstration_273

test_demos:
  - demonstration_215
  - demonstration_216
  - demonstration_232
  - demonstration_233
  - demonstration_255