name: Card Sliding SSL

dataset_path: ${data_path}/demonstrations/ssl

complete_demos:
  - demonstration_152 
  - demonstration_153
  - demonstration_154
  - demonstration_155
  - demonstration_156
  - demonstration_157
  - demonstration_158
  - demonstration_159
  - demonstration_160
  - demonstration_161
  - demonstration_162
  - demonstration_163
  - demonstration_164
  - demonstration_165
  - demonstration_166
  - demonstration_167
  - demonstration_168
  - demonstration_169
  - demonstration_170
  - demonstration_171
  - demonstration_172
  - demonstration_173
  - demonstration_174
  - demonstration_175
  - demonstration_176
  - demonstration_177
  - demonstration_178
  - demonstration_179 
  - demonstration_180
  - demonstration_181
  - demonstration_182
  - demonstration_183
  - demonstration_184
  - demonstration_185
  - demonstration_186
  - demonstration_187
  - demonstration_188
  - demonstration_189
  - demonstration_190
  - demonstration_191
  - demonstration_192
  - demonstration_193 
  - demonstration_194
  - demonstration_195
  - demonstration_196
  - demonstration_197
  - demonstration_198
  - demonstration_199
  - demonstration_200
  - demonstration_201
  - demonstration_202
  - demonstration_203
  - demonstration_204
  - demonstration_205
  - demonstration_206
  - demonstration_207
  - demonstration_208
  - demonstration_209

train_demos:
  - demonstration_152 
  - demonstration_153
  - demonstration_154
  - demonstration_155
  - demonstration_156
  - demonstration_157
  - demonstration_158
  - demonstration_159
  - demonstration_160
  - demonstration_161
  - demonstration_162
  - demonstration_165
  - demonstration_166
  - demonstration_167
  - demonstration_168
  - demonstration_169
  - demonstration_170
  - demonstration_171
  - demonstration_172
  - demonstration_173
  - demonstration_174
  - demonstration_175
  - demonstration_176
  - demonstration_177
  - demonstration_178
  - demonstration_179 
  - demonstration_180
  - demonstration_181
  - demonstration_182
  - demonstration_183
  - demonstration_184
  - demonstration_185
  - demonstration_186
  - demonstration_187
  - demonstration_190
  - demonstration_191
  - demonstration_192
  - demonstration_193 
  - demonstration_194
  - demonstration_195
  - demonstration_196
  - demonstration_197
  - demonstration_198
  - demonstration_199
  - demonstration_200
  - demonstration_201
  - demonstration_202
  - demonstration_204
  - demonstration_205
  - demonstration_206
  - demonstration_207
  - demonstration_208
  - demonstration_209

test_demos:
  - demonstration_163
  - demonstration_164
  - demonstration_188
  - demonstration_189
  - demonstration_203