defaults:
  - _self_
  - /dataset: planar_rotation/clipped_trajectory
  - /encoder: resnet18
  - /image_parameters: planar_rotation
 
arm_position: flat
selected_view: 1

run_store_path: deploy_runs/planar_rotation/${model}

vinn:
  min_action_distance: 0.02 

  data_path: ${task.dataset.dataset_path}
  demos_list: ${task.dataset.complete_demos}

  nn_buffer_limit: 10

  encoder_weights_path: model_weights/BYOL - ${encoder.name} - View ${selected_view} - Planar Rotation SSL/BYOL - ${encoder.name} - View ${selected_view} - Planar Rotation SSL_best.pt
  absolute_actions: ${absolute_actions}

bc:
  predictor:
    input_dim: 512
    output_dim: 12
    hidden_dims: [1024, 2024, 512, 512] 
    use_batchnorm: true

  model_weights: model_weights/Behavior Cloning - ${encoder.name} - View ${selected_view} - Planar Rotation Filtered/Behavior Cloning - ${encoder.name} - View ${selected_view} - Planar Rotation Filtered_best.pt