name: ResNet18 RGB Encoder

settings:
  _target_: holodex.utils.models.load_encoder
  encoder_type: 'resnet18'
  input_channels: 3
  weights_path: ${encoder_weights_path}
  pretrained: true

output_size: 512